#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on Ubuntu             #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

source /var/hostvn/.hostvn.conf
source /var/hostvn/menu/helpers/variable_common

backup_num=$(grep -w "backup_num" "${FILE_INFO}" | cut -f2 -d'=')

for users in /home/*; do
    if [[ -d "${users}" ]]; then
        user=${users##*/}
        for domains in /home/"${user}"/*; do
            if [[ -d "${domains}" ]]; then
                domain=${domains##*/}
                for publics in /home/${user}/${domain}/public_html; do
                    if [[ -d "${publics}" ]]; then
                        public=${publics##*/}
                        db_name=$(grep -w "db_name" "${USER_DIR}/.${domain}.conf" 2>/dev/null | cut -f2 -d'=')

                        backup_dir="/home/backup/${CURRENT_DATE}/${domain}"
                        mkdir -p "${backup_dir}"
                        rm -rf "${backup_dir:?}"/*

                        # Dump database (neu co)
                        if [ -n "${db_name}" ]; then
                            cd "${backup_dir}" || continue
                            mariadb-dump -uadmin -p"${mysql_pwd}" "${db_name}" 2>/dev/null | gzip > "${db_name}".sql.gz
                        fi

                        # Nen source code
                        cd /home/"${user}"/"${domain}" || continue
                        if [[ ! -f "/home/${user}/${domain}/public_html/wp-config.php" && -f "/home/${user}/${domain}/wp-config.php" ]]; then
                            cp /home/"${user}"/"${domain}"/wp-config.php /home/"${user}"/"${domain}"/public_html/wp-config.php
                        fi
                        if [ -d "/home/${user}/${domain}/public_html/storage" ]; then
                            tar -cpzf "${backup_dir}/${domain}.tar.gz" \
                                --exclude "public_html/storage/framework/cache" --exclude "public_html/storage/framework/views" "${public}"
                        else
                            tar -cpzf "${backup_dir}/${domain}.tar.gz" \
                                --exclude "public_html/wp-content/cache" "${public}"
                        fi

                        # Don dep wp-config.php tam
                        if [[ -f "/home/${user}/${domain}/public_html/wp-config.php" && -f "/home/${user}/${domain}/wp-config.php" ]]; then
                            rm -rf /home/"${user}"/"${domain}"/public_html/wp-config.php
                        fi
                    fi
                done
            fi
        done
    fi
done

find /home/backup -type d -mtime +"$backup_num" -exec rm -r {} \;
